testing port changes

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,11 +4,7 @@ name: OpenScap Workbench CI
 
 # Controls when the action will run. Triggers the workflow on push or pull request
 # events but only for the master branch
-on:
-  push:
-    branches: [ '*' ]
-  pull_request:
-    branches: [ master ]
+on: push
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -22,12 +18,36 @@ jobs:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
 
-    # Runs a single command using the runners shell
-    - name: Run a one-line script
-      run: echo Hello, world!
+    # *before_install* port
+    - name: Install additional packages
+      run: |
+        brew update
+        brew install jq
+        brew install qt5
+        brew install asciidoc
 
     # Runs a set of commands using the runners shell
-    - name: Run a multi-line script
+    - name: Run openSCAP build process
       run: |
-        echo Add other actions to build,
-        echo test, and deploy your project.
+        git clone --depth 1 https://github.com/openscap/openscap.git -b master
+        pushd openscap/build
+        cmake -DENABLE_PROBES=FALSE ../
+        make -j 4
+        make install
+        popd
+
+    # Build OSX image
+    - name: Build OSX image
+      run: |
+        chmod +x ./build-for-osx.sh
+        ./build-for-osx.sh
+        REL_TAG=`curl -s "https://github.com/ComplianceAsCode/content/releases/latest" | grep -o 'tag/[v.0-9]*' | awk -F/ '{print $2}'`
+        REL_TAG_NUM=`echo ${REL_TAG} | cut -d"v" -f2`
+        DWN_LINK=https://github.com/ComplianceAsCode/content/releases/download/${REL_TAG}/scap-security-guide-${REL_TAG_NUM}.zip
+        if [ -z "${DWN_LINK}" ] ; then
+            echo "Could not get the ZIP URL! It is empty!"
+            exit 1
+        fi
+        wget "${DWN_LINK}" -O ssg.zip
+        mkdir -p `pwd`/build-osx/scap-workbench.app/Contents/Resources/ssg/ && unzip ssg.zip && cp -a scap-security-guide-*/* `pwd`/build-osx/scap-workbench.app/Contents/Resources/ssg/
+        cd build-osx && sh osx-create-dmg.sh
